export type OilIconDef = { name: string; color: string; botanical: string };

export const OIL_ICONS: Record<string, OilIconDef> = {
  // Citrus
  lemon:            { name: 'fruit-citrus',   color: '#e8a020', botanical: 'citrus' },
  orange:           { name: 'fruit-citrus',   color: '#e87020', botanical: 'citrus' },
  grapefruit:       { name: 'fruit-citrus',   color: '#e05060', botanical: 'citrus' },
  bergamot:         { name: 'fruit-citrus',   color: '#c8c020', botanical: 'citrus' },
  lime:             { name: 'fruit-citrus',   color: '#70c030', botanical: 'citrus' },
  // Minty
  eucalyptus:       { name: 'leaf',           color: '#30a880', botanical: 'eucalyptus-leaf' },
  peppermint:       { name: 'snowflake',      color: '#20b890', botanical: 'mint-sprig' },
  spearmint:        { name: 'sprout',         color: '#40c870', botanical: 'mint-sprig' },
  'tea-tree':       { name: 'leaf',           color: '#38c8a0', botanical: 'eucalyptus-leaf' },
  // Woody — conifer
  cedarwood:        { name: 'pine-tree',      color: '#8b6040', botanical: 'pine-branch' },
  pine:             { name: 'pine-tree',      color: '#406030', botanical: 'pine-branch' },
  fir:              { name: 'pine-tree',      color: '#507040', botanical: 'pine-branch' },
  juniper:          { name: 'pine-tree',      color: '#607850', botanical: 'pine-branch' },
  cypress:          { name: 'pine-tree',      color: '#506840', botanical: 'pine-branch' },
  spruce:           { name: 'pine-tree',      color: '#305040', botanical: 'pine-branch' },
  // Woody — other
  sandalwood:       { name: 'grain',          color: '#c09060', botanical: 'sandalwood-ring' },
  patchouli:        { name: 'leaf-maple',     color: '#706040', botanical: 'maple-leaf' },
  vetiver:          { name: 'grass',          color: '#807050', botanical: 'grass-blade' },
  'ho-wood':        { name: 'leaf',           color: '#a07050', botanical: 'sandalwood-ring' },
  // Herbal
  rosemary:         { name: 'sprout',         color: '#5a8040', botanical: 'sprout' },
  lavender:         { name: 'flower-tulip',   color: '#9070b0', botanical: 'lavender-sprig' },
  chamomile:        { name: 'flower',         color: '#d0b040', botanical: 'chamomile' },
  lemongrass:       { name: 'grass',          color: '#a0c030', botanical: 'grass-blade' },
  basil:            { name: 'sprout',         color: '#60a040', botanical: 'sprout' },
  thyme:            { name: 'sprout',         color: '#709050', botanical: 'sprout' },
  sage:             { name: 'sprout',         color: '#8080a0', botanical: 'sprout' },
  geranium:         { name: 'flower-tulip',   color: '#d06080', botanical: 'lavender-sprig' },
  verbena:          { name: 'sprout',         color: '#b0c040', botanical: 'sprout' },
  palmarosa:        { name: 'flower-tulip',   color: '#d08060', botanical: 'lavender-sprig' },
  tobacco:          { name: 'leaf',           color: '#a06040', botanical: 'grass-blade' },
  // Floral
  rose:             { name: 'flower-tulip',   color: '#d04060', botanical: 'lavender-sprig' },
  'ylang-ylang':    { name: 'flower',         color: '#e0b020', botanical: 'chamomile' },
  jasmine:          { name: 'flower',         color: '#e8c880', botanical: 'chamomile' },
  neroli:           { name: 'flower-tulip',   color: '#e8c040', botanical: 'lavender-sprig' },
  helichrysum:      { name: 'flower',         color: '#d0a020', botanical: 'chamomile' },
  osmanthus:        { name: 'flower',         color: '#e0a040', botanical: 'chamomile' },
  // Spicy
  'black-pepper':   { name: 'seed-outline',   color: '#806050', botanical: 'peppercorn' },
  ginger:           { name: 'fire',           color: '#d07020', botanical: 'ginger-root' },
  cinnamon:         { name: 'fire',           color: '#c06030', botanical: 'ginger-root' },
  clove:            { name: 'seed-outline',   color: '#804030', botanical: 'peppercorn' },
  cardamom:         { name: 'seed-outline',   color: '#90a030', botanical: 'peppercorn' },
  // Resinous
  frankincense:     { name: 'water',          color: '#c09050', botanical: 'resin-drop' },
  myrrh:            { name: 'water',          color: '#906040', botanical: 'resin-drop' },
  benzoin:          { name: 'water',          color: '#d0a060', botanical: 'resin-drop' },
  copal:            { name: 'water',          color: '#d0b070', botanical: 'resin-drop' },
  // Aquatic / misc
  'sea-buckthorn':  { name: 'leaf',           color: '#e08030', botanical: 'citrus' },
  'green-tea':      { name: 'leaf',           color: '#80b060', botanical: 'eucalyptus-leaf' },
  cucumber:         { name: 'water',          color: '#70b050', botanical: 'sprout' },
  // New additions
  marjoram:         { name: 'sprout',         color: '#7a9050', botanical: 'sprout' },
  ravintsara:       { name: 'leaf',           color: '#50b080', botanical: 'eucalyptus-leaf' },
  niaouli:          { name: 'sprout',         color: '#40b098', botanical: 'mint-sprig' },
  cajeput:          { name: 'leaf',           color: '#30b088', botanical: 'eucalyptus-leaf' },
  petitgrain:       { name: 'flower-tulip',   color: '#b0c848', botanical: 'lavender-sprig' },
  mandarin:         { name: 'fruit-citrus',   color: '#f0a020', botanical: 'citrus' },
  'lemon-myrtle':   { name: 'fruit-citrus',   color: '#d8d020', botanical: 'citrus' },
  myrtle:           { name: 'sprout',         color: '#508848', botanical: 'sprout' },
  copaiba:          { name: 'water',          color: '#c09848', botanical: 'resin-drop' },
  'bay-laurel':     { name: 'leaf',           color: '#788840', botanical: 'herb-bundle' },
  spikenard:        { name: 'grass',          color: '#7a6040', botanical: 'grass-blade' },
  'blue-tansy':     { name: 'flower',         color: '#1870a0', botanical: 'chamomile' },
  cistus:           { name: 'water',          color: '#c09060', botanical: 'resin-drop' },
  amyris:           { name: 'grain',          color: '#b8844c', botanical: 'sandalwood-ring' },
  // Sauna store staples
  'eucalyptus-radiata': { name: 'leaf',       color: '#58c090', botanical: 'eucalyptus-leaf' },
  'mountain-pine':  { name: 'pine-tree',      color: '#507830', botanical: 'pine-branch' },
  'norway-spruce':  { name: 'pine-tree',      color: '#385838', botanical: 'pine-branch' },
  'siberian-fir':   { name: 'pine-tree',      color: '#406850', botanical: 'pine-branch' },
  larch:            { name: 'pine-tree',      color: '#a07840', botanical: 'pine-branch' },
  birch:            { name: 'leaf',           color: '#90c060', botanical: 'sprout' },
  anise:            { name: 'seed-outline',   color: '#9080a0', botanical: 'peppercorn' },
  'birch-tar':      { name: 'water',          color: '#5a3020', botanical: 'resin-drop' },
};
